export const artist = {
  name: "Elijah Nang",
  alias: "Nang Soul",
  years: "1991 – 2023",
  domain: "nangsoul.com",
  tagline: "A memorial archive of the music and legacy of Elijah Nang.",
  bio: [
    "Elijah Nang, known through his project name Nang Soul, was a London-based producer, visual artist, and self-described audio novelist whose work turned instrumental music into narrative space. His sound blended lo-fi textures, jazz influence, electronica, and East Asian elements into something uniquely his own — rooted in atmosphere, memory, and movement.",
    "He often described his work as more than music, but as an audio novel. Each project felt like a chapter, carrying listeners through vivid, cinematic worlds shaped by emotion, reflection, and story. Across releases such as Lost in Japan, Gaijin, and Nang Soul, he fused visual imagination, worldbuilding, and a deeply personal sense of storytelling into music that felt immersive rather than incidental.",
    "Photography, videography, illustration, and visual culture were not separate from his music, but part of the same creative language, helping shape the worlds his listeners stepped into. Whether through intimate beat tapes or larger conceptual projects, Elijah made work that invited people to slow down, imagine, and feel.",
    "Elijah passed away in 2023, but the world he created remains. This site exists to preserve access to his work and to honor the legacy he left behind for listeners around the world.",
  ],
  legacy: {
    heading: "Building Worlds",
    text: "Across projects like Gaijin, Lost in Japan, and the Nang Soul series, Elijah Nang built more than songs. He built worlds. His music invited listeners into places that felt reflective, transportive, and unmistakably personal. This archive is here to preserve a path back to that work.",
    quote: "Each project felt like a chapter, carrying listeners through vivid, cinematic worlds filled with emotion, memory, and story.",
  },
  images: {
    hero: "/images/elijah-hero.png",
    about: "/images/elijah-profile.png",
    studio: "/images/elijah-studio.jpg",
    silhouette: "/images/elijah-silhouette.jpg",
    artwork: "/images/elijah-artwork.jpg",
  },
  links: [
    { label: "YouTube", url: "https://www.youtube.com/@elijahnang90" },
    {
      label: "Spotify",
      url: "https://open.spotify.com/artist/0yIO6HI875mLzamqmjjFFU",
    },
    { label: "SoundCloud", url: "https://soundcloud.com/elijahnang" },
    { label: "Instagram", url: "https://www.instagram.com/elijahnang/" },
    { label: "Twitch", url: "https://www.twitch.tv/nangsoul" },
    { label: "Facebook", url: "https://www.facebook.com/elijahnang91" },
  ],
  featuredWorks: [
    {
      title: "Gaijin",
      type: "Album",
      description: "A defining project and sweeping journey through East-Asian inspired soundscapes.",
      listenUrl: "https://open.spotify.com/album/3Mz0drsWHgVg5zTm60ncdl",
      listenLabel: "Listen on Spotify",
    },
    {
      title: "Gaijin II Tale of Rai",
      type: "Album",
      description: "A continuation of the sonic world established in Gaijin, weaving narrative and atmosphere.",
      listenUrl: "https://open.spotify.com/album/79ynbZwBXsmdFZw8Oa0FMK",
      listenLabel: "Listen on Spotify",
    },
    {
      title: "Misogi",
      type: "Album",
      description: "An introspective album rooted in purification and renewal, layered with ambient textures.",
      listenUrl: "https://open.spotify.com/album/43E2P5I9w7eU24Qh9yG9X8",
      listenLabel: "Listen on Spotify",
    },
    {
      title: "The Wonderland",
      type: "Album",
      description: "A dreamlike exploration of sound — whimsical, warm, and hauntingly beautiful.",
      listenUrl: "https://soundcloud.com/elijahnang",
      listenLabel: "Explore on SoundCloud",
    },
    {
      title: "Nang Soul Vol.3 / Akira",
      type: "Beat Tape",
      description: "A project reflecting the broader Nang Soul identity and rhythmic exploration.",
      listenUrl: "https://soundcloud.com/elijahnang/nang-soul-vol3-akira-full-beat-tape",
      listenLabel: "Listen on SoundCloud",
    },
    {
      title: "Lost in Japan",
      type: "Album",
      description: "A foundational work exploring memory and setting through a lo-fi lens.",
      listenUrl: "https://open.spotify.com/album/28T6D6L0M6K8ZJ6w1K7z5P",
      listenLabel: "Listen on Spotify",
    }
  ],
};
