"use client";

import { FormEvent, useEffect, useState } from "react";

type PublicMessage = { displayName: string; location: string | null; message: string; approvedAt: string | null };
declare global { interface Window { turnstile?: { render: (target: HTMLElement, options: { sitekey: string; callback: (token: string) => void; "expired-callback": () => void }) => void } } }
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en", { month: "long", year: "numeric" }).format(new Date(value)) : "";

export default function MemorialBoard() {
  const [messages, setMessages] = useState<PublicMessage[]>([]); const [offset, setOffset] = useState(0); const [hasMore, setHasMore] = useState(false);
  const [message, setMessage] = useState(""); const [feedback, setFeedback] = useState(""); const [sending, setSending] = useState(false); const [turnstileToken, setTurnstileToken] = useState("");
  const load = async (next = 0) => { try { const response = await fetch(`/api/memorial/messages?offset=${next}`); const data = await response.json(); if (!response.ok) throw new Error(); setMessages((current) => next ? [...current, ...data.messages] : data.messages); setOffset(data.nextOffset); setHasMore(data.hasMore); } catch { setFeedback("Messages are temporarily unavailable. Please try again later."); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { const key = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY; if (!key) return; const mount = document.getElementById("turnstile-widget"); const render = () => mount && window.turnstile?.render(mount, { sitekey: key, callback: setTurnstileToken, "expired-callback": () => setTurnstileToken("") }); if (window.turnstile) { render(); return; } const script = document.createElement("script"); script.src = "https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit"; script.async = true; script.defer = true; script.onload = render; document.head.appendChild(script); return () => script.remove(); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setFeedback(""); if (message.length > 1000) return setFeedback("Message must be 1000 characters or fewer."); if (!turnstileToken) return setFeedback("Please complete the verification before submitting."); const form = new FormData(event.currentTarget); setSending(true); try { const response = await fetch("/api/memorial/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName: form.get("displayName"), location: form.get("location"), message, consent: form.get("consent") === "on", website: form.get("website"), turnstileToken }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); event.currentTarget.reset(); setMessage(""); setTurnstileToken(""); setFeedback("Thank you. Your message has been received and will appear here if approved."); } catch (error) { setFeedback(error instanceof Error ? error.message : "We could not send your message. Please try again."); } finally { setSending(false); } }
  return <section id="messages" className="memorial-board" aria-labelledby="messages-heading">
    <div className="memorial-intro"><p className="section-label">Memorial guestbook</p><h2 id="messages-heading">Messages for Elijah</h2><p>Leave a few words about Elijah, his music, or what his work has meant to you.</p></div>
    <div className="memorial-layout"><form className="memorial-form" onSubmit={submit} noValidate><div><label htmlFor="displayName">Display Name</label><input id="displayName" name="displayName" required maxLength={60} autoComplete="name" /></div><div><label htmlFor="location">Location <span>optional</span></label><input id="location" name="location" maxLength={80} autoComplete="address-level2" /></div><div><label htmlFor="message">Message</label><textarea id="message" name="message" required maxLength={1000} value={message} onChange={(event) => setMessage(event.target.value)} /><p className="character-count">{message.length} / 1000</p></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off" /></div><label className="consent"><input type="checkbox" name="consent" required /> <span>By submitting this message, I understand that it may be published publicly on NangSoul after review.</span></label><p className="memorial-note">Please do not include private contact information or sensitive personal information in your message.</p><p className="memorial-note">Messages are reviewed before publication. Spam, advertising, hateful content, impersonation, private information, or messages unrelated to Elijah and his work may not be published.</p><div id="turnstile-widget" /><button className="button-primary" disabled={sending || message.length > 1000} type="submit">{sending ? "Sending…" : "Send message"}</button><p className="form-feedback" role="status" aria-live="polite">{feedback}</p></form>
      <div className="message-list" aria-live="polite">{messages.map((entry, index) => <article className="memorial-entry" key={`${entry.approvedAt}-${entry.displayName}-${index}`}><header><strong>{entry.displayName}</strong>{entry.location && <span>{entry.location}</span>}</header><p>{entry.message}</p><time dateTime={entry.approvedAt || undefined}>{date(entry.approvedAt)}</time></article>)}{!messages.length && !feedback && <p className="memorial-empty">Approved messages will be preserved here.</p>}{hasMore && <button className="button-secondary" onClick={() => load(offset)} type="button">Load more messages</button>}</div></div>
  </section>;
}
