import type { CSSProperties } from "react";

type PetalStyle = CSSProperties & {
  "--petal-left": string;
  "--petal-top": string;
  "--petal-size": string;
  "--petal-duration": string;
  "--petal-delay": string;
  "--petal-drift": string;
  "--petal-mid-drift": string;
  "--petal-opacity": string;
  "--petal-blur": string;
  "--petal-rotate-start": string;
  "--petal-rotate-mid": string;
  "--petal-rotate-end": string;
};

const petals: PetalStyle[] = [
  {
    "--petal-left": "4%",
    "--petal-top": "-7vh",
    "--petal-size": "1.1rem",
    "--petal-duration": "78s",
    "--petal-delay": "-61s",
    "--petal-drift": "12vw",
    "--petal-mid-drift": "5vw",
    "--petal-opacity": "0.16",
    "--petal-blur": "0.2px",
    "--petal-rotate-start": "-18deg",
    "--petal-rotate-mid": "124deg",
    "--petal-rotate-end": "302deg",
  },
  {
    "--petal-left": "9%",
    "--petal-top": "2vh",
    "--petal-size": "0.78rem",
    "--petal-duration": "96s",
    "--petal-delay": "-22s",
    "--petal-drift": "-8vw",
    "--petal-mid-drift": "-3vw",
    "--petal-opacity": "0.12",
    "--petal-blur": "0.8px",
    "--petal-rotate-start": "42deg",
    "--petal-rotate-mid": "182deg",
    "--petal-rotate-end": "346deg",
  },
  {
    "--petal-left": "14%",
    "--petal-top": "-3vh",
    "--petal-size": "1.42rem",
    "--petal-duration": "104s",
    "--petal-delay": "-83s",
    "--petal-drift": "8vw",
    "--petal-mid-drift": "3vw",
    "--petal-opacity": "0.14",
    "--petal-blur": "0.1px",
    "--petal-rotate-start": "12deg",
    "--petal-rotate-mid": "150deg",
    "--petal-rotate-end": "330deg",
  },
  {
    "--petal-left": "20%",
    "--petal-top": "7vh",
    "--petal-size": "0.94rem",
    "--petal-duration": "86s",
    "--petal-delay": "-44s",
    "--petal-drift": "14vw",
    "--petal-mid-drift": "7vw",
    "--petal-opacity": "0.15",
    "--petal-blur": "0.4px",
    "--petal-rotate-start": "-68deg",
    "--petal-rotate-mid": "76deg",
    "--petal-rotate-end": "241deg",
  },
  {
    "--petal-left": "27%",
    "--petal-top": "-10vh",
    "--petal-size": "1rem",
    "--petal-duration": "92s",
    "--petal-delay": "-13s",
    "--petal-drift": "-10vw",
    "--petal-mid-drift": "-4vw",
    "--petal-opacity": "0.1",
    "--petal-blur": "1.1px",
    "--petal-rotate-start": "94deg",
    "--petal-rotate-mid": "218deg",
    "--petal-rotate-end": "384deg",
  },
  {
    "--petal-left": "33%",
    "--petal-top": "4vh",
    "--petal-size": "1.58rem",
    "--petal-duration": "112s",
    "--petal-delay": "-67s",
    "--petal-drift": "9vw",
    "--petal-mid-drift": "4vw",
    "--petal-opacity": "0.11",
    "--petal-blur": "0.7px",
    "--petal-rotate-start": "-24deg",
    "--petal-rotate-mid": "112deg",
    "--petal-rotate-end": "292deg",
  },
  {
    "--petal-left": "39%",
    "--petal-top": "11vh",
    "--petal-size": "0.82rem",
    "--petal-duration": "88s",
    "--petal-delay": "-5s",
    "--petal-drift": "-12vw",
    "--petal-mid-drift": "-5vw",
    "--petal-opacity": "0.13",
    "--petal-blur": "0.5px",
    "--petal-rotate-start": "28deg",
    "--petal-rotate-mid": "206deg",
    "--petal-rotate-end": "358deg",
  },
  {
    "--petal-left": "45%",
    "--petal-top": "-5vh",
    "--petal-size": "1.18rem",
    "--petal-duration": "84s",
    "--petal-delay": "-36s",
    "--petal-drift": "10vw",
    "--petal-mid-drift": "4vw",
    "--petal-opacity": "0.14",
    "--petal-blur": "0.25px",
    "--petal-rotate-start": "-118deg",
    "--petal-rotate-mid": "18deg",
    "--petal-rotate-end": "202deg",
  },
  {
    "--petal-left": "52%",
    "--petal-top": "3vh",
    "--petal-size": "0.72rem",
    "--petal-duration": "108s",
    "--petal-delay": "-72s",
    "--petal-drift": "-6vw",
    "--petal-mid-drift": "-2vw",
    "--petal-opacity": "0.1",
    "--petal-blur": "1px",
    "--petal-rotate-start": "81deg",
    "--petal-rotate-mid": "198deg",
    "--petal-rotate-end": "374deg",
  },
  {
    "--petal-left": "58%",
    "--petal-top": "-8vh",
    "--petal-size": "1.26rem",
    "--petal-duration": "94s",
    "--petal-delay": "-19s",
    "--petal-drift": "13vw",
    "--petal-mid-drift": "6vw",
    "--petal-opacity": "0.12",
    "--petal-blur": "0.55px",
    "--petal-rotate-start": "-38deg",
    "--petal-rotate-mid": "130deg",
    "--petal-rotate-end": "316deg",
  },
  {
    "--petal-left": "64%",
    "--petal-top": "12vh",
    "--petal-size": "0.9rem",
    "--petal-duration": "82s",
    "--petal-delay": "-54s",
    "--petal-drift": "-13vw",
    "--petal-mid-drift": "-6vw",
    "--petal-opacity": "0.13",
    "--petal-blur": "0.35px",
    "--petal-rotate-start": "146deg",
    "--petal-rotate-mid": "286deg",
    "--petal-rotate-end": "448deg",
  },
  {
    "--petal-left": "70%",
    "--petal-top": "-4vh",
    "--petal-size": "1.42rem",
    "--petal-duration": "116s",
    "--petal-delay": "-91s",
    "--petal-drift": "7vw",
    "--petal-mid-drift": "3vw",
    "--petal-opacity": "0.1",
    "--petal-blur": "1.2px",
    "--petal-rotate-start": "-82deg",
    "--petal-rotate-mid": "62deg",
    "--petal-rotate-end": "236deg",
  },
  {
    "--petal-left": "77%",
    "--petal-top": "5vh",
    "--petal-size": "0.84rem",
    "--petal-duration": "90s",
    "--petal-delay": "-31s",
    "--petal-drift": "-9vw",
    "--petal-mid-drift": "-4vw",
    "--petal-opacity": "0.12",
    "--petal-blur": "0.65px",
    "--petal-rotate-start": "18deg",
    "--petal-rotate-mid": "166deg",
    "--petal-rotate-end": "344deg",
  },
  {
    "--petal-left": "83%",
    "--petal-top": "-11vh",
    "--petal-size": "1.12rem",
    "--petal-duration": "86s",
    "--petal-delay": "-66s",
    "--petal-drift": "8vw",
    "--petal-mid-drift": "4vw",
    "--petal-opacity": "0.15",
    "--petal-blur": "0.3px",
    "--petal-rotate-start": "-8deg",
    "--petal-rotate-mid": "140deg",
    "--petal-rotate-end": "322deg",
  },
  {
    "--petal-left": "90%",
    "--petal-top": "8vh",
    "--petal-size": "0.74rem",
    "--petal-duration": "102s",
    "--petal-delay": "-48s",
    "--petal-drift": "-11vw",
    "--petal-mid-drift": "-5vw",
    "--petal-opacity": "0.11",
    "--petal-blur": "0.9px",
    "--petal-rotate-start": "72deg",
    "--petal-rotate-mid": "248deg",
    "--petal-rotate-end": "426deg",
  },
  {
    "--petal-left": "97%",
    "--petal-top": "-6vh",
    "--petal-size": "1.28rem",
    "--petal-duration": "110s",
    "--petal-delay": "-11s",
    "--petal-drift": "-16vw",
    "--petal-mid-drift": "-7vw",
    "--petal-opacity": "0.1",
    "--petal-blur": "1px",
    "--petal-rotate-start": "-52deg",
    "--petal-rotate-mid": "94deg",
    "--petal-rotate-end": "276deg",
  },
  {
    "--petal-left": "12%",
    "--petal-top": "19vh",
    "--petal-size": "0.7rem",
    "--petal-duration": "99s",
    "--petal-delay": "-74s",
    "--petal-drift": "9vw",
    "--petal-mid-drift": "4vw",
    "--petal-opacity": "0.09",
    "--petal-blur": "1.25px",
    "--petal-rotate-start": "132deg",
    "--petal-rotate-mid": "246deg",
    "--petal-rotate-end": "402deg",
  },
  {
    "--petal-left": "31%",
    "--petal-top": "17vh",
    "--petal-size": "0.86rem",
    "--petal-duration": "106s",
    "--petal-delay": "-27s",
    "--petal-drift": "-7vw",
    "--petal-mid-drift": "-3vw",
    "--petal-opacity": "0.1",
    "--petal-blur": "1.05px",
    "--petal-rotate-start": "-96deg",
    "--petal-rotate-mid": "42deg",
    "--petal-rotate-end": "222deg",
  },
  {
    "--petal-left": "49%",
    "--petal-top": "21vh",
    "--petal-size": "0.68rem",
    "--petal-duration": "118s",
    "--petal-delay": "-96s",
    "--petal-drift": "6vw",
    "--petal-mid-drift": "2vw",
    "--petal-opacity": "0.08",
    "--petal-blur": "1.4px",
    "--petal-rotate-start": "38deg",
    "--petal-rotate-mid": "184deg",
    "--petal-rotate-end": "366deg",
  },
  {
    "--petal-left": "72%",
    "--petal-top": "18vh",
    "--petal-size": "0.8rem",
    "--petal-duration": "96s",
    "--petal-delay": "-58s",
    "--petal-drift": "-8vw",
    "--petal-mid-drift": "-3vw",
    "--petal-opacity": "0.1",
    "--petal-blur": "1.15px",
    "--petal-rotate-start": "-34deg",
    "--petal-rotate-mid": "120deg",
    "--petal-rotate-end": "304deg",
  },
];

export default function SakuraAtmosphere() {
  return (
    <div className="sakura-atmosphere" aria-hidden="true">
      <div className="sakura-canopy" />
      <div className="sakura-petal-field">
        {petals.map((style, index) => (
          <span
            // The list is intentionally static so the breeze timing is stable.
            key={index}
            className="sakura-petal"
            style={style}
          />
        ))}
      </div>
    </div>
  );
}
